plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
