#!/usr/bin/env ruby
# frozen_string_literal: true

require "propertree/application"

Propertree::LOG.level = Logger::INFO

verbose_flag = ARGV.delete("-v")
app = Propertree::Application.new(verbose: !verbose_flag.nil?)

# TODO: use Thor for better flag handling ergonomics
app.load_streets(ARGV[0])
app.load_properties(ARGV[1])

Propertree::LOG.info <<~ANSWER
  average cost of a property
  - on a street with tall trees: #{app.average_price_tall_trees}
  - on a street with short trees: #{app.average_price_short_trees}
ANSWER
