name: Ruby Gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.4

    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: Bearer ${{secrets.GITHUB_TOKEN}}\n" > $HOME/.gem/credentials
        gem build propertree*.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/estraph propertree*.gem
    - name: Install and run the gem
      run: |
        gem install propertree -s https://github:${{secrets.GITHUB_TOKEN}}@rubygems.pkg.github.com/estraph -v ${{ github.ref_name }}
        calculate_averages dublin-trees.json dublin-property.csv
